### PR TITLE
add authentication-popup.html translations

### PR DESCRIPTION
**Pull request by rossluk**
Add missing translations for Magento_Customer/view/frontend/web/template/authentication-popup.html. It shows after click to "Go to checkout" button when "Allow guest checkout" admin option is off.

### CODE REVIEW

**Comment by Imaginaerum** [comment]
Thanks a lot... 
This request need a development. My csv files are generated by a script. The default magento extract works badly. I create my own script. I add your request into my dev.
Do you speak french ?

**Comment by rossluk** [comment]
Sorry but I don't, just work with French edition. I didn't generate this file by megento, i'm just added few phrases to your file in alphabetical order by using github edit interface. If it helps I can send you only lines which I changed.

**Comment by Imaginaerum** [comment]
I'll send you a message when update is ready. Coming soon.

**Comment by Imaginaerum** [comment]
Update is ready 100.4.2. Can you tell me if all is ok ?

**Comment by rossluk** [comment]
All look well, thanks. Can you also add to the fix this two lines?
"Next Step","Prochaine étape"
"Review & Payments","Vérification et paiement"
It's from one page checkout page.
Thanks.

**Comment by Imaginaerum** [comment]
It must be added ?

**Comment by rossluk** [comment]
I think yes. Because now it doesn't have translations.

**Comment by rossluk** [comment]
And... :)
"Adding...","Ajouter..."
It appears when you click to "Add to cart" button.

**Comment by Imaginaerum** [comment]
I can't find phrases on magento files... Can you send me path for files ?

**Comment by quienti** [comment]
Je n'ai pas les traductions sur mon Magento, même après avoir utilisé `magento cache:flush` et suuprimé le `pub/static`

I don't have translations on my Magento, even after used `magento cache:flush` and removed all `pub/static`

**Comment by quienti** [comment]
.. Je déteste mon navigateur, ça marche sur un autre, je n'ai rien dit ^^

.. I hate my browser. It's work on an another, I said nothing ^^

**Comment by rossluk** [comment]
@Imaginaerum "Adding...","Ajouter..." -  it's located in the Magento_Catalog/view/frontend/web/js/catalog-add-to-cart.js
"Next Step" - it's my mistake.
"Review & Payments" - it's Magento_Checkout/view/frontend/web/js/view/payment.js (Magento 2.0.2 hasn't translation function for that but it's fixed here - https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/web/js/view/payment.js)
@quienti you should clean your browser cache and localStorage (translations saved in it).

**Comment by quienti** [comment]
@rossluk I know ^^ ;)

**Comment by Imaginaerum** [comment]
I found a solution to extract all missing phrases on js. Coming soon... ;)
See https://github.com/Imaginaerum/magento2-language-fr-fr/issues/21

**Comment by Imaginaerum** [comment]
Updated ! Can you try ? thanks a lot...

**Comment by rossluk** [comment]
Good job! But I can't see "Review & Payments".

**Comment by Imaginaerum** [comment]
I see for it... Thanks ;)

**Comment by Imaginaerum** [comment]
No chance... This phrase is not a translate item...

```
define(
    [
        'jquery',
        "underscore",
        'uiComponent',
        'ko',
        'Magento_Checkout/js/model/quote',
        'Magento_Checkout/js/model/step-navigator',
        'Magento_Checkout/js/model/payment-service',
        'Magento_Checkout/js/model/payment/method-converter',
        'Magento_Checkout/js/action/get-payment-information',
        'Magento_Checkout/js/model/checkout-data-resolver'
    ],
```

```
initialize: function () {
                this._super();
                checkoutDataResolver.resolvePaymentMethod();
                stepNavigator.registerStep(
                    'payment',
                    null,
                    'Review & Payments',
                    this.isVisible,
                    _.bind(this.navigate, this),
                    20
                );
                return this;
            },
```

This code do not use $t('Review & Payments') and js translation 'mage/translate' into the define

I can't add this phrase into my package for the moment... Can't work...

**Pull request closed without merging**
